=== ssirowy/xml-schema-tests/section-schema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- All supported languages, defined as an attribute -->
  <xs:attribute name="language">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="cpp"/>
        <xs:enumeration value="c"/>
        <xs:enumeration value="java"/>
        <xs:enumeration value="python"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:attribute>

  <xs:attribute name="guid">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:pattern value="[a-zA-Z0-9]{8}"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:attribute>
  
  <xs:complexType name="definitiontype" mixed="true">
    <xs:sequence>
      <xs:element ref="term"/>
    </xs:sequence>
  </xs:complexType>

  <!-- Section type. A section has a set of properties -->
  <xs:complexType name="Section">
    <xs:all>
      <xs:element name="title" type="xs:string"/>
      <xs:element name="zypInfos" type="ZypInfos" minOccurs="0"/>
      <xs:element name="contentResources" type="ContentResources" />
    </xs:all>
  </xs:complexType>
  
  <!-- Content resources array type. -->
  <xs:complexType name="ContentResources">
    <xs:sequence>
      <xs:element name="contentResource" type="ContentResource" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  
  <!-- Array of zypInfos array type -->
  <xs:complexType name="ZypInfos">
    <xs:sequence>
      <xs:element name="zypInfo" type="ZypInfo" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  
  <!-- zypInfo type -->
  <xs:complexType name="ZypInfo">
    <xs:all>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="timestamp" type="xs:dateTime"/>
      <xs:element name="text" type="xs:string"/>
    </xs:all>
  </xs:complexType>

  <!-- Content resource type (Abstract). -->
  <xs:complexType abstract="true" name="ContentResource">
    <xs:sequence/>
    <xs:attribute ref="guid" use="required" />
  </xs:complexType>

  <!-- Support marks for mixed content text regions -->
  <xs:element name="term" type="xs:string"/>
  <xs:element name='definition' type='definitiontype' />

  <!-- Text content resource type. -->
  <xs:complexType name="TextResource" mixed="true">
    <xs:complexContent>
      <xs:extension base="ContentResource">
        <xs:choice maxOccurs="unbounded" minOccurs="0">
          <xs:element ref="definition"/>
        </xs:choice>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  <!-- A code type for specifying a code block --> 
  <xs:complexType name="CodeResource">
    <xs:complexContent>
      <xs:extension base="ContentResource">
        <xs:attribute ref="language" use="required" />
        <xs:attribute name="file" use="required">
          <xs:simpleType>
            <xs:restriction base="xs:string"/>
          </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="compileCommand">
          <xs:simpleType>
            <xs:restriction base="xs:string"/>
          </xs:simpleType>
        </xs:attribute>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <!-- Image content resource type. -->
  <xs:complexType name="ImageResource">
    <xs:complexContent>
      <xs:extension base="ContentResource">
        <xs:sequence>
          <xs:element name="url" type="xs:anyURI"/>
          <xs:element name="caption" type="xs:string"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <!-- Multiple choice question resource type. -->
  <xs:complexType name="MultipleChoiceResource">
    <xs:complexContent>
      <xs:extension base="ContentResource">
        <xs:sequence>
          <xs:element name="question" type="MultipleChoiceQuestion" maxOccurs="unbounded"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  <!-- Comment  resource type. -->
  <xs:complexType name="CommentResource">
    <xs:complexContent>
      <xs:extension base="ContentResource">
        <xs:all>
          <xs:element name="name" type="xs:string"/>
          <xs:element name="timestamp" type="xs:dateTime"/>
          <xs:element name="comment" type="xs:string"/>
        </xs:all>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <!-- Type for a question -->
  <xs:complexType name="MultipleChoiceQuestion">
    <xs:sequence>
      <xs:element name="text" type="xs:string"/>
      <xs:element name="choice" type="QuestionChoice" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <!-- Type for a question choice -->
  <xs:complexType name="QuestionChoice">
    <xs:sequence>
      <xs:element name="correct" type="xs:boolean"/>
      <xs:element name="label" type="xs:string"/>
      <xs:element name="explanation" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
  
  <!-- XML has a section as the root element -->
  <xs:element name="section" type="Section"/>

</xs:schema>

=== ssirowy/xml-schema-tests/chapter1/section3/section.xml
<?xml version="1.0"?>
<section xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../section-schema.xsd">
  <zypInfos>
    <zypInfo>
      <name>Adrian Lizarraga</name>
      <timestamp>2017-06-07T09:00:00</timestamp>
      <text>Created new section</text>
    </zypInfo>
  </zypInfos>
  <title>Basic output</title>
  <contentResources>
    <contentResource xsi:type="TextResource" guid="11345678">
      Printing of output to a screen is a common programming task. This section describes basic output; later sections have more details.
    </contentResource>
    <contentResource xsi:type="CodeResource" guid="12345678" language="cpp" file="main.cpp"/>
  </contentResources>
</section>

=== ssirowy/xml-schema-tests/chapter1/section2/section.xml
<?xml version="1.0"?>
<section xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../section-schema.xsd">
  <zypInfos>
    <zypInfo>
      <name>Adrian Lizarraga</name>
      <timestamp>2017-06-07T09:00:00</timestamp>
      <text>Created new section</text>
    </zypInfo>
    <zypInfo>
      <name>Adrian Lizarraga</name>
      <timestamp>2017-06-07T09:02:00</timestamp>
      <text>Added image</text>
    </zypInfo>
  </zypInfos>
  <title>Section 2</title>
  <contentResources>
    <contentResource xsi:type="TextResource" guid="11345678">
      Always wear proper eye protection.

      <definition> <term>The simpsons</term> is a show</definition>
    </contentResource>
    <contentResource xsi:type="CommentResource" guid="13467789">
      <name>Adrian Lizarraga</name>
      <timestamp>2017-06-07T09:00:00</timestamp>
      <comment>TODO: Finish writing content later</comment>
    </contentResource>
    <contentResource xsi:type="ImageResource" guid="15e72367">
      <url>https://goo.gl/kMR3GM</url>
      <caption>Scott Sirowy the 1st</caption>
    </contentResource>
  </contentResources>
</section>

=== ssirowy/xml-schema-tests/chapter1/section1/section.xml
<?xml version="1.0"?>
<section xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../section-schema.xsd">
  <zypInfos>
      <zypInfo>
          <name>Scott Sirowy</name>
          <timestamp>2017-06-01T09:00:00</timestamp>
          <text>Worked on schema for 5 minutes</text>
      </zypInfo>
      <zypInfo>
          <name>Adrian Lizarraga</name>
          <timestamp>2017-06-01T09:00:00</timestamp>
          <text>Worked on schema some more</text>
      </zypInfo>
      <zypInfo>
          <name>Scott Sirowy</name>
          <timestamp>2017-06-06T09:00:00</timestamp>
          <text>Worked on demo styling</text>
      </zypInfo>
            <zypInfo>
          <name>Scott Sirowy</name>
          <timestamp>2017-06-06T09:00:00</timestamp>
          <text>Got comments to work</text>
      </zypInfo>
  </zypInfos>
   <title>Programming </title>
 <contentResources>
   <contentResource xsi:type="TextResource" guid="12345678">
     A recipe consists of instructions that a chef executes, like adding eggs or stirring ingredients. Likewise, <definition>a <term>computer program</term> consists of instructions that a computer executes (or runs), like multiplying numbers or printing a number to a screen.</definition>
</contentResource>
   <contentResource xsi:type="ImageResource" guid="5e712367">
    <url>https://zytools.zybooks.com/zyAuthor/ProgInCCppJava/50/IMAGES/embedded_image01spZA9RiRIvVsll3GwWFwLQKCCAATWbs3N9sVBcgs8dg_10_bTiqgzpCFQ.png</url>
    <caption>A  program is like a recipe</caption>
  </contentResource>
  <contentResource xsi:type="TextResource" guid="12345678">
    <definition><term>Code</term> can be defined easily using new setup.</definition>.   See below for an accessible code block.  Note this code
    was defined in its own file, which could even allow us to compile such code before ever processing to ensure the code can actually run. 
    
    Newlines are respected in source, which helps to remove the need for tags like br
    </contentResource>
  <contentResource xsi:type="CodeResource" guid="12345678" language="cpp">
      <code>
 #include &lt;iostream&gt;
using namespace std;

int main() {
    cout &lt;&lt; "Scott was here";
}
      </code>
  </contentResource>
  <contentResource xsi:type="MultipleChoiceResource" guid="22345679">
    <question>
      <text>What is the approximate shape of the planet Earth?</text>
      <choice>
        <correct>false</correct>
        <label>Flat</label>
        <explanation>The world  is not flat...  Are u sure?</explanation>
      </choice>
      <choice>
        <correct>true</correct>
        <label>Round</label>
        <explanation>The world is round.</explanation>
      </choice>
    </question>
    <question>
      <text>What is 2 + 2?</text>
      <choice>
        <correct>true</correct>
        <label>4</label>
        <explanation>Yeah it's 4.</explanation>
      </choice>
      <choice>
        <correct>false</correct>
        <label>5</label>
        <explanation>Nope. Try using your fingers to count.</explanation>
      </choice>
    </question>
  </contentResource>
   <contentResource xsi:type="CommentResource" guid="34567789">
    <name>Scott Sirowy</name>
    <timestamp>2017-05-30T09:00:00</timestamp>
    <comment>Sample comment</comment>
  </contentResource>
  <contentResource xsi:type="ImageResource" guid="56712367">
    <url>http://www.cs.ucr.edu/~vahid/vahid06.jpg</url>
    <caption>Franklin Delano Vahid</caption>
  </contentResource>
</contentResources>
</section>
